# ----
# Site

title: Yes!!
url: "https://j2yes.github.io"
baseurl: "https://j2yes.github.io"
google_analytics_key: UA-92237726-1
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Development Story.
author:
  name: j2yes
  email: j2yess@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name: Software Engineer Blog
  links:
    - https://j2yes.github.io

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major

# theme: jekyll-theme-cayman